"""Generate C source templates for LD_PRELOAD filter injection libraries.

Creates .c source files that, when compiled with an ARM toolchain, produce
shared libraries (.so) that intercept ALSA MIDI calls to inject filter
parameter changes into the MPC application at runtime.
"""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent


def generate_filter_inject_source(
    filter_cc_cutoff: int = 74,
    filter_cc_resonance: int = 71,
    initial_cutoff: int = 127,
    initial_resonance: int = 0,
    output_path: str | Path | None = None,
) -> str:
    """Generate a C source file for an LD_PRELOAD filter injection library.

    The generated library intercepts snd_rawmidi_write() calls and can inject
    MIDI CC messages to control MPC filter parameters from custom logic.

    Args:
        filter_cc_cutoff: MIDI CC number for filter cutoff.
        filter_cc_resonance: MIDI CC number for filter resonance.
        initial_cutoff: Initial cutoff value (0-127).
        initial_resonance: Initial resonance value (0-127).
        output_path: If provided, write the .c file to this path.

    Returns:
        The C source code as a string.
    """
    source = dedent(f"""\
        /*
         * Filter Injection Library for Akai MPC (LD_PRELOAD)
         * Generated by akai-replacement-filters
         *
         * Compile with ARM toolchain:
         *   arm-linux-gnueabihf-gcc -shared -fPIC -o filter_inject.so filter_inject.c -ldl -lasound
         *
         * Usage:
         *   LD_PRELOAD=./filter_inject.so /usr/bin/MPC
         */

        #define _GNU_SOURCE
        #include <stdio.h>
        #include <stdlib.h>
        #include <string.h>
        #include <dlfcn.h>
        #include <alsa/asoundlib.h>

        /* Filter parameter CC numbers */
        #define FILTER_CC_CUTOFF    {filter_cc_cutoff}
        #define FILTER_CC_RESONANCE {filter_cc_resonance}

        /* Initial filter values */
        static unsigned char g_cutoff = {initial_cutoff};
        static unsigned char g_resonance = {initial_resonance};

        /* Original function pointer */
        typedef ssize_t (*orig_rawmidi_write_t)(snd_rawmidi_t *, const void *, size_t);
        static orig_rawmidi_write_t orig_rawmidi_write = NULL;

        static void init_orig(void) {{
            if (!orig_rawmidi_write) {{
                orig_rawmidi_write = (orig_rawmidi_write_t)dlsym(RTLD_NEXT, "snd_rawmidi_write");
                if (!orig_rawmidi_write) {{
                    fprintf(stderr, "[filter_inject] Failed to find snd_rawmidi_write\\n");
                }}
            }}
        }}

        /*
         * Build a MIDI CC message.
         * Format: [0xB0 | channel, cc_number, value]
         */
        static void build_cc_msg(unsigned char *buf, unsigned char channel,
                                  unsigned char cc, unsigned char value) {{
            buf[0] = 0xB0 | (channel & 0x0F);
            buf[1] = cc & 0x7F;
            buf[2] = value & 0x7F;
        }}

        /*
         * Intercepted snd_rawmidi_write.
         * Monitors outgoing MIDI and can inject filter CC changes.
         */
        ssize_t snd_rawmidi_write(snd_rawmidi_t *rmidi, const void *buffer, size_t size) {{
            init_orig();

            const unsigned char *data = (const unsigned char *)buffer;

            /* Monitor incoming CC messages for filter parameters */
            if (size >= 3 && (data[0] & 0xF0) == 0xB0) {{
                unsigned char cc = data[1];
                unsigned char val = data[2];

                if (cc == FILTER_CC_CUTOFF) {{
                    g_cutoff = val;
                }} else if (cc == FILTER_CC_RESONANCE) {{
                    g_resonance = val;
                }}
            }}

            /* Pass through to original function */
            if (orig_rawmidi_write) {{
                return orig_rawmidi_write(rmidi, buffer, size);
            }}
            return (ssize_t)size;
        }}

        /*
         * Inject current filter values as CC messages.
         * Call this from a timer or event handler to push filter state.
         */
        void inject_filter_state(snd_rawmidi_t *rmidi, unsigned char channel) {{
            unsigned char cc_msg[3];

            init_orig();
            if (!orig_rawmidi_write) return;

            build_cc_msg(cc_msg, channel, FILTER_CC_CUTOFF, g_cutoff);
            orig_rawmidi_write(rmidi, cc_msg, 3);

            build_cc_msg(cc_msg, channel, FILTER_CC_RESONANCE, g_resonance);
            orig_rawmidi_write(rmidi, cc_msg, 3);
        }}

        /*
         * Constructor: called when library is loaded via LD_PRELOAD.
         */
        __attribute__((constructor))
        static void filter_inject_init(void) {{
            fprintf(stderr, "[filter_inject] Loaded. Cutoff CC=%d, Resonance CC=%d\\n",
                    FILTER_CC_CUTOFF, FILTER_CC_RESONANCE);
            fprintf(stderr, "[filter_inject] Initial values: cutoff=%d, resonance=%d\\n",
                    g_cutoff, g_resonance);
        }}
    """)

    if output_path:
        output_path = Path(output_path)
        output_path.write_text(source)

    return source


def generate_makefile(output_path: str | Path | None = None) -> str:
    """Generate a Makefile for cross-compiling the filter injection library.

    Returns:
        Makefile content as a string.
    """
    makefile = dedent("""\
        # Makefile for filter injection LD_PRELOAD library
        # Requires ARM cross-compilation toolchain

        CC = arm-linux-gnueabihf-gcc
        CFLAGS = -shared -fPIC -Wall -O2
        LDFLAGS = -ldl -lasound

        TARGET = filter_inject.so
        SRC = filter_inject.c

        .PHONY: all clean

        all: $(TARGET)

        $(TARGET): $(SRC)
        \t$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

        clean:
        \trm -f $(TARGET)
    """)

    if output_path:
        Path(output_path).write_text(makefile)

    return makefile
