"""Generate optimized LD_PRELOAD launch scripts for MPC/Force devices.

Creates shell scripts that use TheKikGen/MPC-LiveXplore LD_PRELOAD technique
to inject custom shared libraries before the MPC application starts.
"""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent


def generate_preload_script(
    libraries: list[str],
    mpc_binary: str = "/usr/bin/MPC",
    device_type: str = "mpc_live",
    extra_env: dict[str, str] | None = None,
    output_path: str | Path | None = None,
) -> str:
    """Generate an optimized LD_PRELOAD launch script.

    Args:
        libraries: List of .so library paths to preload (order matters).
        mpc_binary: Path to the MPC binary on the device.
        device_type: Target device ("mpc_live", "mpc_x", "mpc_one", "force").
        extra_env: Additional environment variables to set.
        output_path: If provided, write the script to this path.

    Returns:
        The shell script as a string.
    """
    device_configs = {
        "mpc_live": {"display": "MPC Live", "binary": "/usr/bin/MPC"},
        "mpc_x": {"display": "MPC X", "binary": "/usr/bin/MPC"},
        "mpc_one": {"display": "MPC One", "binary": "/usr/bin/MPC"},
        "force": {"display": "Akai Force", "binary": "/usr/bin/MPC"},
    }

    config = device_configs.get(device_type, device_configs["mpc_live"])
    binary = mpc_binary or config["binary"]
    lib_list = ":".join(libraries)

    env_lines = ""
    if extra_env:
        env_lines = "\n".join(f'export {k}="{v}"' for k, v in extra_env.items())
        env_lines = f"\n# Custom environment\n{env_lines}\n"

    script = dedent(f"""\
        #!/bin/bash
        # LD_PRELOAD launch script for {config['display']}
        # Generated by akai-replacement-filters
        #
        # Libraries loaded (in order):
        #   {chr(10).join(f'#   - {lib}' for lib in libraries)}
        #
        # Usage: Copy this script and .so files to the device,
        #        then run via SSH or MockbaMod bootstrap.

        set -euo pipefail
        {env_lines}
        # Verify libraries exist
        LIBS="{lib_list}"
        IFS=':' read -ra LIB_ARRAY <<< "$LIBS"
        for lib in "${{LIB_ARRAY[@]}}"; do
            if [ ! -f "$lib" ]; then
                echo "ERROR: Library not found: $lib"
                exit 1
            fi
        done

        # Stop existing MPC process if running
        if pidof -q MPC 2>/dev/null; then
            echo "Stopping existing MPC process..."
            killall MPC 2>/dev/null || true
            sleep 2
        fi

        echo "Starting {config['display']} with LD_PRELOAD..."
        echo "Libraries: $LIBS"

        # Launch with preloaded libraries
        export LD_PRELOAD="$LIBS"
        exec {binary} "$@"
    """)

    if output_path:
        output_path = Path(output_path)
        output_path.write_text(script)
        output_path.chmod(0o755)

    return script
