"""Generate LD_PRELOAD library templates specifically for Akai Force firmware.

The Force uses different binary paths and system call patterns than MPC
standalone devices, requiring Force-specific library templates.
"""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent


def generate_preload_library_template(
    library_name: str = "force_filter_hook",
    hook_functions: list[str] | None = None,
    output_dir: str | Path | None = None,
) -> dict[str, str]:
    """Generate a C source template and Makefile for a Force LD_PRELOAD library.

    Args:
        library_name: Name for the generated library (without .so extension).
        hook_functions: List of function names to intercept. Defaults to
                       common ALSA and audio functions.
        output_dir: If provided, write files to this directory.

    Returns:
        Dict mapping filename to content: {"library_name.c": ..., "Makefile": ...}
    """
    if hook_functions is None:
        hook_functions = [
            "snd_rawmidi_write",
            "snd_pcm_writei",
            "snd_seq_event_output",
        ]

    # Generate hook function stubs
    hook_stubs = []
    for func_name in hook_functions:
        stub = dedent(f"""\
            /* Hook for {func_name} */
            /* TODO: Add interception logic for your filter module */
            /*
            return_type {func_name}(params) {{
                static orig_fn_t orig = NULL;
                if (!orig) orig = (orig_fn_t)dlsym(RTLD_NEXT, "{func_name}");
                // Pre-processing: inject filter parameters here
                return_type result = orig(params);
                // Post-processing
                return result;
            }}
            */
        """)
        hook_stubs.append(stub)

    c_source = dedent(f"""\
        /*
         * {library_name}.c - LD_PRELOAD Library for Akai Force
         * Generated by akai-replacement-filters
         *
         * Compile:
         *   arm-linux-gnueabihf-gcc -shared -fPIC -o {library_name}.so {library_name}.c -ldl -lasound
         *
         * Deploy:
         *   Copy to MockbaMod SD card AddOns folder, reference in startup.sh
         */

        #define _GNU_SOURCE
        #include <stdio.h>
        #include <stdlib.h>
        #include <string.h>
        #include <dlfcn.h>

        /* Force-specific paths */
        #define FORCE_MPC_BINARY "/usr/bin/MPC"
        #define FORCE_MIDI_DEVICE "/dev/snd/midiC0D0"

        /* Hook function declarations */
        {"".join(hook_stubs)}

        /* Constructor: runs when library is loaded */
        __attribute__((constructor))
        static void {library_name}_init(void) {{
            fprintf(stderr, "[{library_name}] Loaded on Akai Force\\n");
            fprintf(stderr, "[{library_name}] Hooked functions: {', '.join(hook_functions)}\\n");
        }}

        /* Destructor: runs when library is unloaded */
        __attribute__((destructor))
        static void {library_name}_fini(void) {{
            fprintf(stderr, "[{library_name}] Unloaded\\n");
        }}
    """)

    makefile = dedent(f"""\
        # Makefile for {library_name} (Akai Force LD_PRELOAD library)
        CC = arm-linux-gnueabihf-gcc
        CFLAGS = -shared -fPIC -Wall -O2
        LDFLAGS = -ldl -lasound

        TARGET = {library_name}.so
        SRC = {library_name}.c

        .PHONY: all clean deploy

        all: $(TARGET)

        $(TARGET): $(SRC)
        \t$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

        clean:
        \trm -f $(TARGET)

        # Deploy to MockbaMod SD card (adjust path as needed)
        deploy: $(TARGET)
        \tcp $(TARGET) /media/662522/AddOns/$(TARGET)
    """)

    files = {
        f"{library_name}.c": c_source,
        "Makefile": makefile,
    }

    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        for filename, content in files.items():
            (output_dir / filename).write_text(content)

    return files
